services:
  app:
    build: .
    container_name: pln_hse_dashboard
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      streamlit run Homepage.py
      --server.runOnSave=true
      --server.fileWatcherType=poll
    restart: unless-stopped
